name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        run-test-on: [ desktop, mobile ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: make ${{ matrix.run-test-on }}

      - name: Generate report
        if: always()
        run: make generate-report

      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: report-${{ matrix.run-test-on }}
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
          fail-on-error: 'false'

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: html-report-${{ matrix.run-test-on }}
          path: target/generated-report
